title: Digitus Carpendi
author: Jonathan Martin Ramirez
email: zhangyuzhangyu.yahoo.com
description: > # this means to ignore newlines until "baseurl:"
  Avante Garde Work Station For Intrepid Ideas

theme: minima

# social links
github_username:  DigitusCarpendi # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
